### ISSUE TITLE
update existing chart?

### ISSUE THREAD

**Issue by vtombez** [chekos/Datawrapper#12] opened 2020-11-26 08:35 UTC
* datawrapper version: datawrapper-0.4.3
* Python version: 3.8

### Description

It looks easy to create and publish any charts with your library, but I was wondering how do you update an already published chart.

In other words, what is the best way to retrieve a chart and update its data? I didn’t see anything about that in your documentation but maybe I missed it ;) 

### UPDATE

I just figured how to do it  :) 

Thanks for the library!

**Comment by adelaide01** [comment] 2021-03-14 03:28
@vtombez Can you share how to update the chart? I can't find it in the documentation.

**Comment by hackerlikecomputer** [comment] 2021-03-14 19:47
> @vtombez Can you share how to update the chart? I can't find it in the documentation.

Seconding this -- can you share how you're doing this? Trying to figure out how to do this without implementing a method for the api method "/charts/{id}/data/refresh"

**Comment by vtombez** [comment] 2021-03-15 08:02
hi,

@adelaide01 to update a chart with new data, you can simply use add_data(id, data), where data is a dataframe created with pandas. See below an example where i also update some properties.

@hackerlikecomputer I don't use external data so i don't need to refresh my chart. But I think that if you republish your chart, with publish_chart(id), it refreshes it. In fact I also do it after updating my chart to be sure everything is right, even if it's maybe not necessary (see below)

def datawrapper_update(id, df):
    dw = Datawrapper(access_token = ACCESS_DATAWRAPPER)
    properties = last_maj()
    dw.add_data(id, df)
    dw.update_metadata(id, properties)
    dw.publish_chart(id)

last_maj() is a simple function to add when I updated the chart ;)

**Comment by hackerlikecomputer** [comment] 2021-03-15 13:51
Thanks! Still think the refresh_data method is necessary for my case because I have non-dev team members who use the datawrapper GUI to set up graphics with external data sources. I want them to still be able to do that while also having a script that fetches data and forces the charts to update after they're created.

**Comment by vtombez** [comment] 2021-03-15 14:01
yeah but why not use the publish_chart method then? I think it does the job.

Something like this should work:

#!/usr/bin/env python3
# coding: utf-8

import time
from datawrapper import Datawrapper

def refresh_charts(id):
    dw = Datawrapper(access_token = ACCESS_DATAWRAPPER)
    dw.publish_chart(id)
    time.sleep(10)

if __name__ == '__main__':
    ls_charts_id = []
    for id in ls_charts_id:
        refresh_charts(id)

**Comment by hackerlikecomputer** [comment] 2021-03-15 18:51
That definitely should work, but the datawrapper API has an [officially-supported way of refreshing data](https://developer.datawrapper.de/reference#chartsiddatarefresh). I'd rather use that API endpoint to avoid any potential unexpected behavior that may or may not happen as a result of re-publishing the chart.

**Comment by chekos** [comment] 2021-03-25 20:52
@hackerlikecomputer 's PR with the `.refresh_data()` method was just merged! That should be the go-to way to update charts as it is the officially-supported way. Thanks!

**Closed by chekos** 2021-03-25 20:52 UTC
